services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gastos_sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Gastos.API/Dockerfile
    container_name: gastos_api
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=GastosDB;User Id=sa;Password=Your_password123;TrustServerCertificate=True;

volumes:
  sql_data: